### PR TITLE
Env Variables viewer panel inside Studio

### PR DESCRIPTION
**Pull request by marceloadsj**
@supnate , this is the PR to the viewer of Env Vars.

For now, only viewer. In my free time I will work on add more options (create, edit, delete)...

:-)

### CODE REVIEW

**Comment by supnate** [comment]
Wow thanks @marceloadsj for the big PR! I will look at it tomorrow as I’m on travel now.

**Comment by supnate** [comment]
Hey @marceloadsj , I just checked out the PR and it works great! Since I'm just working on the next major release of Rekit which will support a full plugin system(including UI). So I will help this to be a plugin.

BTW, one issue of the current PR is that it fetches file content via vio.getContent which caches file content so if .env files are changed, the UI will not show the changes because Rekit doesn't watch file changes out of src folder. Suppose this will be fixed when it's finally released.

Anyway, thanks again for your contribution!

**Comment by marceloadsj** [comment]
Hello @supnate. Thank you for the feedback!
Oh, yeah, when the new full plugin system I can migrate the env manager to be a plugin (more modular approach, really good).

About the file watcher, yeah, I'm thinking about the reload of the file to application itself too. Cause to apply .env changes, a restart (stop & start) the entire node process are needed.

Well, let's get it on!
I will look at the open issues to help, in my free time, with more PRs, maybe fix some possibly bugs or so. 😃

**Comment by supnate** [comment]
Thanks @marceloadsj ! Looking forward to your more help on the project :-D

**Pull request merged**
